export default () => {
  return [
    'Affe',
    'Arzt',
    'Astronaut',
    'Aufräumen',
    'Baby',
    'Ballerina',
    'Ballon aufpusten',
    'Blumen pflücken',
    'Bogenschießen',
    'Boxen',
    'Bowling spielen',
    'Busfahrer',
    'Bücherei',
    'Delfin',
    'Detektiv',
    'Dirigent',
    'Duschen',
    'Eichhörnchen',
    'Eis essen',
    'Einkaufen',
    'Elefant',
    'Erfinder',
    'Esel',
    'Eule',
    'Fahrrad fahren',
    'Faultier',
    'Fernseher schauen',
    'Fotograf',
    'Friseur',
    'Fußball spielen',
    'Golf spielen',
    'Hai',
    'Hexe',
    'Huhn',
    'Hund',
    'Hase',
    'Igel',
    'Ins Kino gehen',
    'Katze',
    'Känguru',
    'Kellner',
    'Kindergarten',
    'Koch',
    'Krokodil',
    'Lehrer',
    'Löwe',
    'Maulwurf',
    'Maus',
    'Musik hören',
    'Ninja',
    'Opernsängerin',
    'Papa',
    'Pferd',
    'Pinguin',
    'Polizist',
    'Schlagzeug spielen',
    'Schneemann bauen',
    'Schwimmen',
    'T-Rex',
    'Tennis spielen',
    'Tauchen',
    'Teddy',
    'Tanzen',
    'Telefonieren',
    'Rennfahrer',
    'Vampir',
    'Videospiele spielen',
    'Weihnachstmann',
    'Wolf',
    'Zauberer',
    'Zähne putzen',
    'Zirkusclown',
    'Zoo besuchen',
    'Zwiebeln schneiden',
  ] as Array<string>;
}
